"""add_address

Revision ID: eb4482be34f1
Revises: cbf1e084fc22
Create Date: 2023-06-27 16:21:03.800643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4482be34f1'
down_revision = 'cbf1e084fc22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('address', sa.String(), nullable=True))
    op.drop_index('ix_properties_id', table_name='properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_properties_id', 'properties', ['id'], unique=False)
    op.drop_column('properties', 'address')
    # ### end Alembic commands ###
